name = "water-tank"
main = "worker.js"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "TANK_STATE"
class_name = "TankState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TankState"]